server:
  port: 6969
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: uday
    url: jdbc:mysql://localhost:3306/springrest
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true